# 工作流名称
name: 构建 ImmortalWrt

# 触发条件：手动触发
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: '是否启用 SSH 连接到 Actions 虚拟机 (方便调试)'
        required: false
        default: 'false'

# 任务
jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest

    # 步骤
    steps:
      # 1. 检出你的仓库代码
      - name: 检出代码
        uses: actions/checkout@v3

      # 2. 安装编译依赖
      - name: 安装依赖环境
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync \
          unzip zlib1g-dev file wget

      # 3. 更新并安装 Feeds
      # 这个命令会自动使用你仓库里的 feeds.conf.default 文件
      - name: 更新与安装 Feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 4. 拷贝你的自定义编译配置
      # ！！！ 这是为你特别修改的地方 ！！！
      - name: 拷贝编译配置
        run: cp immortal.config .config

      # 5. 生成最终 .config 文件
      - name: 生成最终 .config
        run: make defconfig

      # 6. 下载软件包源码
      - name: 下载软件包
        run: make download -j$(nproc)

      # 7. 开始编译固件 (V=s 输出详细日志)
      - name: 编译固件
        run: make -j$(nproc) V=s

      # 8. 整理并上传固件
      - name: 上传固件到 Artifacts
        uses: actions/upload-artifact@v3
        with:
          # 上传后的产物名称
          name: ImmortalWrt_Firmware
          # 要上传的文件路径
          path: bin/targets/*/*/*.*
